// src/routes/dashboard/payouts/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { apiEnvelope, apiFetch } from '$lib/api';
	import { formatPrice } from '$lib/format';
	import { inputCls, labelCls } from '$lib/ui-classes';
	import SectionHeader from '$lib/components/SectionHeader.svelte';
	import Panel from '$lib/components/Panel.svelte';
	import Kicker from '$lib/components/Kicker.svelte';
	import Btn from '$lib/components/Btn.svelte';
	import Badge from '$lib/components/Badge.svelte';
	import EmptyState from '$lib/components/EmptyState.svelte';
	import Modal from '$lib/components/Modal.svelte';
	import Skeleton from '$lib/components/Skeleton.svelte';
	import Spinner from '$lib/components/Spinner.svelte';

	interface Contributor {
		id: string;
		email: string;
		realName: string | null;
		pending: number;
		paidOut: number;
		lifetimeEarned: number;
	}

	interface Payout {
		id: string;
		amount: number;
		method: string;
		reference: string | null;
		status: string;
		createdAt: string;
		contributor: { email: string; realName: string | null } | null;
	}

	interface Settlement {
		id: string;
		period: string;
		totalPool: number;
		totalDistributed: number;
		ranAt: string;
	}

	type PayMethod = 'BANK_TRANSFER' | 'EWALLET' | 'CASH';

	let contributors = $state<Contributor[]>([]);
	let payouts = $state<Payout[]>([]);
	let settlements = $state<Settlement[]>([]);
	let loading = $state(true);

	let selected = $state<Contributor | null>(null);
	let amount = $state('');
	let method = $state<PayMethod>('BANK_TRANSFER');
	let reference = $state('');
	let saving = $state(false);
	let message = $state('');

	let settlePeriod = $state('');
	let settleMsg = $state('');
	let settling = $state(false);

	async function fetchAll() {
		loading = true;
		try {
			const [c, p, s] = await Promise.all([
				apiEnvelope<Contributor[]>('/payouts/contributors'),
				apiEnvelope<Payout[]>('/payouts?limit=20'),
				apiEnvelope<Settlement[]>('/payouts/settlements')
			]);
			contributors = c.data ?? [];
			payouts = p.data ?? [];
			settlements = s.data ?? [];
		} catch (err) {
			console.error(err);
		} finally {
			loading = false;
		}
	}

	async function submitPayout(e: SubmitEvent) {
		e.preventDefault();
		if (!selected) return;
		const pending = selected.pending;
		const parsed = Number(amount);
		if (!amount.trim() || Number.isNaN(parsed)) {
			message = 'Nominal tidak valid';
			return;
		}
		if (parsed <= 0) {
			message = 'Nominal harus lebih dari 0';
			return;
		}
		if (parsed > pending) {
			message = `Nominal melebihi saldo tertunda (${formatPrice(pending)})`;
			return;
		}
		const recipient = selected.realName || selected.email;
		if (
			!confirm(`Bayar ${formatPrice(parsed)} kepada ${recipient} via ${method}?`)
		)
			return;
		saving = true;
		message = '';
		try {
			const res = await apiFetch('/payouts', {
				method: 'POST',
				body: JSON.stringify({
					contributorId: selected.id,
					amount: Number(amount),
					method,
					reference: reference || undefined
				})
			});
			if (!res.ok) {
				const j = await res.json().catch(() => null);
				throw new Error(j?.message ?? j?.error?.message ?? 'Gagal mencatat payout');
			}
			selected = null;
			amount = '';
			reference = '';
			await fetchAll();
		} catch (err) {
			message = err instanceof Error ? err.message : 'Gagal mencatat payout';
		} finally {
			saving = false;
		}
	}

	async function runSettlement(e: SubmitEvent) {
		e.preventDefault();
		const period = settlePeriod.trim();
		if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(period)) {
			settleMsg = 'Format periode tidak valid (gunakan YYYY-MM, mis. 2026-06)';
			return;
		}
		if (
			!confirm(
				`Jalankan settlement periode ${period}? Aksi ini tidak dapat dibatalkan (irreversible) — saldo kontributor akan dihitung ulang untuk periode tersebut`
			)
		)
			return;
		settleMsg = '';
		settling = true;
		try {
			const res = await apiFetch('/payouts/settle', {
				method: 'POST',
				body: JSON.stringify({ period })
			});
			const j = await res.json().catch(() => null);
			if (!res.ok) throw new Error(j?.message ?? j?.error?.message ?? 'Gagal run settlement');
			const d = j?.data ?? {};
			settleMsg = `Selesai · pool ${formatPrice(d.totalPool ?? 0)} · dibagi ${formatPrice(d.totalDistributed ?? 0)}`;
			await fetchAll();
		} catch (err) {
			settleMsg = err instanceof Error ? err.message : 'Gagal run settlement';
		} finally {
			settling = false;
		}
	}

	function openPay(c: Contributor) {
		selected = c;
		amount = String(c.pending);
		message = '';
	}

	onMount(fetchAll);
</script>

<div class="rise">
	<SectionHeader index="01" kicker="Pencairan" title="Bagi Hasil" class="mb-10" />

	<Panel class="mb-8">
		<div class="px-7 py-5 border-b hairline border-solid">
			<Kicker class="mb-1.5">02 — Settlement</Kicker>
			<p class="font-display text-lg">Settlement langganan</p>
		</div>
		<div class="px-7 py-6">
			<form onsubmit={runSettlement} class="flex flex-wrap items-center gap-3 mb-5">
				<input
					type="text"
					bind:value={settlePeriod}
					placeholder="YYYY-MM (mis. 2026-06)"
					class="{inputCls} w-52 font-mono"
				/>
				<Btn type="submit" variant="dark" disabled={!settlePeriod || settling}>
					{#if settling}<Spinner />Memproses{:else}Run Settlement{/if}
				</Btn>
				{#if settleMsg}
					<span class="font-mono text-[11px] text-ash">{settleMsg}</span>
				{/if}
			</form>

			{#if loading}
				<Skeleton class="h-16" />
			{:else if settlements.length === 0}
				<EmptyState>Belum ada settlement</EmptyState>
			{:else}
				<ul class="divide-y divide-ink/10 border-t">
					{#each settlements as s}
						<li class="flex items-center justify-between py-3.5">
							<span class="font-mono text-sm tnum">{s.period}</span>
							<span class="font-mono text-[11px] text-ash">
								pool {formatPrice(s.totalPool)} · dibagi
								<span class="text-safelight">{formatPrice(s.totalDistributed)}</span>
							</span>
						</li>
					{/each}
				</ul>
			{/if}
		</div>
	</Panel>

	<Panel class="mb-8">
		<div class="px-7 py-5 border-b hairline border-solid">
			<Kicker class="mb-1.5">03 — Saldo</Kicker>
			<p class="font-display text-lg">Kontributor</p>
		</div>
		{#if loading}
			<div class="p-7 space-y-4">
				<Skeleton class="h-14" /><Skeleton class="h-14" /><Skeleton class="h-14" />
			</div>
		{:else if contributors.length === 0}
			<EmptyState>Belum ada kontributor</EmptyState>
		{:else}
			<ul class="divide-y divide-ink/10">
				{#each contributors as c}
					<li class="flex items-center justify-between gap-4 px-7 py-4">
						<div class="min-w-0">
							<p class="text-ink truncate">{c.realName || c.email}</p>
							<p class="font-mono text-[11px] text-ash-2 truncate">{c.email}</p>
						</div>
						<div class="flex items-center gap-6 shrink-0">
							<div class="text-right">
								<p class="font-display text-lg tnum">{formatPrice(c.pending)}</p>
								<p class="font-mono text-[10px] uppercase tracking-wider text-ash-2">tertunda</p>
							</div>
							<Btn variant="primary" onclick={() => openPay(c)} disabled={c.pending <= 0}>Bayar</Btn>
						</div>
					</li>
				{/each}
			</ul>
		{/if}
	</Panel>

	<Panel>
		<div class="px-7 py-5 border-b hairline border-solid">
			<Kicker class="mb-1.5">04 — Riwayat</Kicker>
			<p class="font-display text-lg">Pencairan terbaru</p>
		</div>
		{#if loading}
			<div class="p-7 space-y-4">
				<Skeleton class="h-14" /><Skeleton class="h-14" /><Skeleton class="h-14" />
			</div>
		{:else if payouts.length === 0}
			<EmptyState>Belum ada pencairan</EmptyState>
		{:else}
			<ul class="divide-y divide-ink/10">
				{#each payouts as p}
					<li class="flex items-center justify-between gap-4 px-7 py-4">
						<div class="min-w-0">
							<p class="text-ink truncate">{p.contributor?.realName || p.contributor?.email || '—'}</p>
							<p class="font-mono text-[11px] text-ash-2">
								{p.method} · {new Date(p.createdAt).toLocaleString('id-ID')}{p.reference ? ` · ref ${p.reference}` : ''}
							</p>
						</div>
						<div class="flex items-center gap-4 shrink-0">
							<Badge status={p.status} />
							<span class="font-display text-base tnum">{formatPrice(p.amount)}</span>
						</div>
					</li>
				{/each}
			</ul>
		{/if}
	</Panel>

	{#if selected}
		<Modal kicker="Bayar Kontributor" title={selected.realName || selected.email} onclose={() => (selected = null)}>
			<p class="font-mono text-[11px] text-ash mb-6">Saldo tertunda {selected ? formatPrice(selected.pending) : ''}</p>

			<form onsubmit={submitPayout} class="space-y-4">
				<div class="grid gap-5 sm:grid-cols-2">
					<div>
						<label class={labelCls} for="pay-amount">Nominal</label>
						<input
							id="pay-amount"
							type="number"
							min={1}
							max={selected.pending}
							bind:value={amount}
							class="{inputCls} font-display tnum"
							placeholder="0"
						/>
					</div>
					<div>
						<label class={labelCls} for="pay-method">Metode</label>
						<select id="pay-method" bind:value={method} class={inputCls}>
							<option value="BANK_TRANSFER">Bank Transfer</option>
							<option value="EWALLET">E-Wallet</option>
							<option value="CASH">Cash</option>
						</select>
					</div>
				</div>
					<div>
						<label class={labelCls} for="pay-ref">Referensi (opsional)</label>
						<input
							id="pay-ref"
							type="text"
							bind:value={reference}
							class={inputCls}
							placeholder="No. bukti / referensi"
						/>
					</div>

					{#if message}
						<p class="text-safelight-dim text-xs font-mono border-l-2 border-safelight pl-3 py-1">{message}</p>
					{/if}

					<div class="flex gap-2 pt-2">
						<Btn variant="ghost" onclick={() => (selected = null)} class="flex-1">Batal</Btn>
						<Btn type="submit" variant="primary" disabled={saving} class="flex-1">
							{#if saving}<Spinner />Memproses{:else}Bayar{/if}
						</Btn>
					</div>
				</form>
		</Modal>
	{/if}
</div>

// src/app/dashboard/payouts/page.tsx
"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/axios";
import { formatPrice } from "@/lib/format";
import {
  SectionHeader,
  Panel,
  Kicker,
  Btn,
  Badge,
  EmptyState,
  Skeleton,
  Spinner,
} from "@/components/ui";

interface Contributor {
  id: string;
  email: string;
  realName: string | null;
  pending: number;
  paidOut: number;
  lifetimeEarned: number;
}

interface Payout {
  id: string;
  amount: number;
  method: string;
  reference: string | null;
  status: string;
  createdAt: string;
  contributor: { email: string; realName: string | null } | null;
}

interface Settlement {
  id: string;
  period: string;
  totalPool: number;
  totalDistributed: number;
  ranAt: string;
}

const inputCls =
  "border hairline border-solid rounded-[3px] bg-card-2 px-3.5 py-2.5 text-sm outline-none transition-colors focus:border-safelight focus:ring-2 focus:ring-safelight/15 placeholder:text-ash-2";

export default function AdminPayoutsPage() {
  const [contributors, setContributors] = useState<Contributor[]>([]);
  const [payouts, setPayouts] = useState<Payout[]>([]);
  const [settlements, setSettlements] = useState<Settlement[]>([]);
  const [loading, setLoading] = useState(true);

  // payout modal state
  const [selected, setSelected] = useState<Contributor | null>(null);
  const [amount, setAmount] = useState("");
  const [method, setMethod] = useState("BANK_TRANSFER");
  const [reference, setReference] = useState("");
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");

  // settlement state
  const [settlePeriod, setSettlePeriod] = useState("");
  const [settleMsg, setSettleMsg] = useState("");
  const [settling, setSettling] = useState(false);

  async function fetchAll() {
    try {
      const [c, p, s] = await Promise.all([
        api.get("/payouts/contributors"),
        api.get("/payouts", { params: { limit: 20 } }),
        api.get("/payouts/settlements"),
      ]);
      setContributors(c.data.data || []);
      setPayouts(p.data.data || []);
      setSettlements(s.data.data || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    fetchAll();
  }, []);

  async function submitPayout(e: React.FormEvent) {
    e.preventDefault();
    if (!selected) return;
    setSaving(true);
    setMessage("");
    try {
      await api.post("/payouts", {
        contributorId: selected.id,
        amount: Number(amount),
        method,
        reference: reference || undefined,
      });
      setSelected(null);
      setAmount("");
      setReference("");
      fetchAll();
    } catch (err: any) {
      setMessage(err?.response?.data?.message || "Gagal mencatat payout");
    } finally {
      setSaving(false);
    }
  }

  async function runSettlement(e: React.FormEvent) {
    e.preventDefault();
    setSettleMsg("");
    setSettling(true);
    try {
      const res = await api.post("/payouts/settle", { period: settlePeriod });
      setSettleMsg(
        `Selesai · pool ${formatPrice(res.data.data.totalPool)} · dibagi ${formatPrice(res.data.data.totalDistributed)}`,
      );
      fetchAll();
    } catch (err: any) {
      setSettleMsg(err?.response?.data?.message || "Gagal run settlement");
    } finally {
      setSettling(false);
    }
  }

  return (
    <div className="rise">
      <SectionHeader
        index="01"
        kicker="Pencairan"
        title="Bagi Hasil"
        className="mb-10"
      />

      {/* Settlement */}
      <Panel className="mb-8">
        <div className="px-7 py-5 border-b hairline border-solid">
          <Kicker className="mb-1.5">02 — Settlement</Kicker>
          <p className="font-display text-lg">Settlement langganan</p>
        </div>
        <div className="px-7 py-6">
          <form onSubmit={runSettlement} className="flex flex-wrap items-center gap-3 mb-5">
            <input
              type="text"
              value={settlePeriod}
              onChange={(e) => setSettlePeriod(e.target.value)}
              placeholder="YYYY-MM (mis. 2026-06)"
              className={`${inputCls} w-52 font-mono`}
            />
            <Btn type="submit" variant="dark" disabled={!settlePeriod || settling}>
              {settling ? <Spinner /> : null}
              {settling ? "Memproses" : "Run Settlement"}
            </Btn>
            {settleMsg && (
              <span className="font-mono text-[11px] text-ash">{settleMsg}</span>
            )}
          </form>

          {loading ? (
            <Skeleton className="h-16" />
          ) : settlements.length === 0 ? (
            <EmptyState>Belum ada settlement</EmptyState>
          ) : (
            <ul className="divide-y divide-ink/10 border-t">
              {settlements.map((s) => (
                <li
                  key={s.id}
                  className="flex items-center justify-between py-3.5"
                >
                  <span className="font-mono text-sm tnum">{s.period}</span>
                  <span className="font-mono text-[11px] text-ash">
                    pool {formatPrice(s.totalPool)} · dibagi{" "}
                    <span className="text-safelight">{formatPrice(s.totalDistributed)}</span>
                  </span>
                </li>
              ))}
            </ul>
          )}
        </div>
      </Panel>

      {/* Contributors with balance */}
      <Panel className="mb-8">
        <div className="px-7 py-5 border-b hairline border-solid">
          <Kicker className="mb-1.5">03 — Saldo</Kicker>
          <p className="font-display text-lg">Kontributor</p>
        </div>
        {loading ? (
          <div className="p-7 space-y-4">
            {Array.from({ length: 3 }).map((_, i) => (
              <Skeleton key={i} className="h-14" />
            ))}
          </div>
        ) : contributors.length === 0 ? (
          <EmptyState>Belum ada kontributor</EmptyState>
        ) : (
          <ul className="divide-y divide-ink/10">
            {contributors.map((c) => (
              <li
                key={c.id}
                className="flex items-center justify-between gap-4 px-7 py-4"
              >
                <div className="min-w-0">
                  <p className="text-ink truncate">{c.realName || c.email}</p>
                  <p className="font-mono text-[11px] text-ash-2 truncate">
                    {c.email}
                  </p>
                </div>
                <div className="flex items-center gap-6 shrink-0">
                  <div className="text-right">
                    <p className="font-display text-lg tnum">
                      {formatPrice(c.pending)}
                    </p>
                    <p className="font-mono text-[10px] uppercase tracking-wider text-ash-2">
                      tertunda
                    </p>
                  </div>
                  <Btn
                    variant="primary"
                    onClick={() => {
                      setSelected(c);
                      setAmount(String(c.pending));
                      setMessage("");
                    }}
                    disabled={c.pending <= 0}
                  >
                    Bayar
                  </Btn>
                </div>
              </li>
            ))}
          </ul>
        )}
      </Panel>

      {/* Recent payouts */}
      <Panel>
        <div className="px-7 py-5 border-b hairline border-solid">
          <Kicker className="mb-1.5">04 — Riwayat</Kicker>
          <p className="font-display text-lg">Pencairan terbaru</p>
        </div>
        {loading ? (
          <div className="p-7 space-y-4">
            {Array.from({ length: 3 }).map((_, i) => (
              <Skeleton key={i} className="h-14" />
            ))}
          </div>
        ) : payouts.length === 0 ? (
          <EmptyState>Belum ada pencairan</EmptyState>
        ) : (
          <ul className="divide-y divide-ink/10">
            {payouts.map((p) => (
              <li
                key={p.id}
                className="flex items-center justify-between gap-4 px-7 py-4"
              >
                <div className="min-w-0">
                  <p className="text-ink truncate">
                    {p.contributor?.realName || p.contributor?.email || "—"}
                  </p>
                  <p className="font-mono text-[11px] text-ash-2">
                    {p.method} · {new Date(p.createdAt).toLocaleString("id-ID")}
                    {p.reference ? ` · ref ${p.reference}` : ""}
                  </p>
                </div>
                <div className="flex items-center gap-4 shrink-0">
                  <Badge status={p.status} />
                  <span className="font-display text-base tnum">
                    {formatPrice(p.amount)}
                  </span>
                </div>
              </li>
            ))}
          </ul>
        )}
      </Panel>

      {/* Payout modal */}
      {selected && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-ink/70 backdrop-blur-sm fade"
          onClick={() => setSelected(null)}
        >
          <div
            className="w-full max-w-sm bg-paper rounded-[3px] border hairline border-solid p-7 rise"
            onClick={(e) => e.stopPropagation()}
          >
            <Kicker className="mb-3">Bayar Kontributor</Kicker>
            <h2 className="font-display text-2xl tracking-[-0.01em] mb-1">
              {selected.realName || selected.email}
            </h2>
            <p className="font-mono text-[11px] text-ash mb-6">
              Saldo tertunda {formatPrice(selected.pending)}
            </p>

            <form onSubmit={submitPayout} className="space-y-4">
              <div>
                <label className="block font-mono text-[10px] uppercase tracking-[0.16em] text-ash mb-2">
                  Nominal
                </label>
                <input
                  type="number"
                  min={1}
                  max={selected.pending}
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  className={`${inputCls} w-full font-display tnum`}
                  placeholder="0"
                />
              </div>
              <div>
                <label className="block font-mono text-[10px] uppercase tracking-[0.16em] text-ash mb-2">
                  Metode
                </label>
                <select
                  value={method}
                  onChange={(e) => setMethod(e.target.value)}
                  className={`${inputCls} w-full`}
                >
                  <option value="BANK_TRANSFER">Bank Transfer</option>
                  <option value="EWALLET">E-Wallet</option>
                  <option value="CASH">Cash</option>
                </select>
              </div>
              <div>
                <label className="block font-mono text-[10px] uppercase tracking-[0.16em] text-ash mb-2">
                  Referensi (opsional)
                </label>
                <input
                  type="text"
                  value={reference}
                  onChange={(e) => setReference(e.target.value)}
                  className={`${inputCls} w-full`}
                  placeholder="No. bukti / referensi"
                />
              </div>

              {message && (
                <p className="text-safelight-dim text-xs font-mono border-l-2 border-safelight pl-3 py-1">
                  {message}
                </p>
              )}

              <div className="flex gap-2 pt-2">
                <Btn
                  variant="ghost"
                  onClick={() => setSelected(null)}
                  className="flex-1"
                >
                  Batal
                </Btn>
                <Btn
                  type="submit"
                  variant="primary"
                  disabled={saving}
                  className="flex-1"
                >
                  {saving ? <Spinner /> : null}
                  {saving ? "Memproses" : "Bayar"}
                </Btn>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
